[model]
learning_rate = 0.001
loss = "cross_entropy"
layers = [
  "layer_000_conv/layer_000_conv.toml", 
  "layer_001_conv/layer_001_conv.toml", 
  "layer_002_flat/layer_002_flat.toml", 
  "layer_003_dense/layer_003_dense.toml",
]
