layer_type = "conv"
kernel_shape = [ 5, 5, 1,]
activation = "relu"
nodes_num = 4
stride = 1
tensors_path = "/Users/phepato/Documents/dev/Lemon/ImageRecogMl/models/pato3/layer_000_conv/layer_000_conv.npz"
