layer_type = "conv"
kernel_shape = [ 3, 3, 4,]
activation = "relu"
nodes_num = 8
stride = 1

[tensors_path]
absolute = "/Users/phepato/Documents/dev/Lemon/ImageRecogMl/models/test_normalization/layer_001_conv/layer_001_conv.npz"
relative = "layer_001_conv/layer_001_conv.npz"
